config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :pins do
  member do
  put "like", to: "pins#upvote"
end
end
root "pins#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  acts_as_votable

  validates :title, presence: true
  validates :description, presence: true
  has_attached_file :image, style: { :medium => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
         acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:edit, :show, :update, :destroy, :upvote ]
  before_action :authenticate_user!, :except => [:index, :show]
  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show

  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Pin successfully created"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, flash[:notice] = "Update was successful"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to pin_path(@pin)
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end
  def set_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pins_helper.rb
module PinsHelper
  
end

app/views/layouts/_messages.html.erb
<div class="container">
<dic class="row">
<div class="col-lg-4 col-md-6 ml-auto mr-auto">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pins/_form.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">

      <%= simple_form_for @pin, html: { mltipart: true } do |f| %>
          <%= render 'shared/errors' %>
          <div class="form-group">
              <%= f.file_field :image, class: "form-control",:size => "300x300", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.text_field :title, autofocus: false, class: 'form-control', placeholder: "Add a Title for your pin" %>
          </div>

          <div class="form-group">
            <%= f.text_area :description, rows:5, class: "form-control", placeholder: "Write a description for your pin" %>
          </div>
          <div form-group>
            <%=  f.button "submit", class: "btn btn-success btn-lg", data: {disable_with:"<i class='fa fa-spinner fa-spin'></i> Creating Pin..."} %>
          </div>
          <% end %>
            [<%= link_to "Cancel request and return to pins listing", pins_path %>]
    </div>
</div>

app/views/pins/edit.html.erb
<h2 class="text-center">Edit Pin</h2>
<%= render 'form' %>

app/views/pins/index.html.erb
<div class="container">
<div id="pins" class="transitions-enabled infinite-scroll clearfix">
<% @pins.each do |pin| %>
<div class="box panel panel-default">
  <%= link_to (image_tag pin.image.url) %>
  <div class="panel-body">
  <h2><%= link_to pin.title, pin_path(pin) %></h2>
  <div class="user">Submitted by: <%= pin.user.email %></div>
</div>
</div>
<% end %>
</div>
</div>

app/views/pins/new.html.erb
<h2 class="text-center">Add a new Pin</h2>
<%= render 'form'%>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">

<div class="box">
          <%= image_tag(@pin.image, :class => "img-rounded img-responsive" )%>
          <h2><p class="title">
           <%= @pin.title %>
         </p></h2>
      <h2><p class="description">
       <%= @pin.description %>
     </p></h2>
      <p>
        <strong>
          Posted by <%= @pin.user.email %>
        </strong>
      </p>
      <% if current_user == @pin.user %>
      <div class="btn-group">
        <%= link_to like_pin_path(@pin), method: :put, class:"btn btn-default" do %>
          <%= @pin.get_upvotes.size %><i class="fa fa-heart" aria-hidden="true"></i><% end %>
        <%= link_to 'Edit', edit_pin_path(@pin), class:"btn btn-primary" %>

        <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "are you sure" }, class:"btn btn-danger" %>
        <% end %>
  </div>
</div>

</div>

app/views/shared/_errors.html.erb
<% if @pin.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@pin.errors.count, "error") %>.
    </div>
    <ul>
    <% @pin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md">
      <%= link_to "PinBoard", root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <!--<li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>-->
        </ul>
        <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-link"><%= link_to "New Pin", new_pin_path %></li>
          <li class="nav-link"><%= link_to "Account", edit_user_registration_path %></li>
          <li class="nav-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
          <li class="nav-link"><%= link_to "Log In", new_user_session_path %></li>
        </ul>
        <% end %>
      </div>
    </nav>